
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dentaldb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    fail-on-unsupported-database: false



  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
jwt:
  # In production override JWT secret with environment variable JWT_SECRET
 # secret: "${JWT_SECRET:change-this-secret-please-update}"
  expiration-ms: 86400000
  secret: "3Fks7eP0cX9LlQa8Jw92ZmDK4HBt6RNs"
  access-expiration-minutes: 15
  refresh-expiration-days: 30

cors:
  allowed-origins: "http://localhost:5000"

server:
  port: 8080
