
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/connectDB
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    fail-on-unsupported-database: false
    repair: true

  web:
    cors:
      allowed-origins: http://localhost:5000
      allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true



  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

app:
  frontend:
    url: http://localhost:5000
  jwt:
    secret: 3Fks7eP0cX9LlQa8Jw92ZmDK4HBt6RNs
    expiration-ms: 86400000
    access-expiration-minutes: 15
    refresh-expiration-days: 30

server:
  port: 8181
